### ISSUE TITLE
Unable to trigger callback for finding the altitude of the drone

### ISSUE THREAD

**Issue by vignesh02** [Parrot-Developers/Samples#24] opened 2015-03-10 02:34 UTC
Hi djavan-bertrand,

In Linux environment using Bebop Drone SDK 3.0, I tried finding the altitude of the drone. I was able to retrieve the method and the call back method from the library, and using that, the method was triggered but not the call back. Here is the code that i used, please let me know where I am going wrong. Thanks in Anticipation.

void ARDrone3PilotingStateAltitudeChangedCallback(double altitude, void *custom)
{
	LOG( INFO ) << "Altitude is " << altitude;
}

bool CBebopInterface::setAltitudeListener()
{
	LOG( INFO ) << "Entering method  - setAltitudeListener.";
	void *custom ;
	ARCOMMANDS_Decoder_SetARDrone3PilotingStateAltitudeChangedCallback(ARDrone3PilotingStateAltitudeChangedCallback,custom);
	return true;

}

**Comment by djavan-bertrand** [comment] 2015-03-10 09:01
Hi, 
Do you test your code while the Bebop is flying ? The altitude is sent only when the Bebop is flying.

**Comment by vladutalexandru** [comment] 2015-03-10 10:14
How did you made your codes to work, because 21 days ago you said you have a compiling error that i currently have. 

Building target: BebopRebopAPI
Invoking: GCC C++ Linker
g++ -L../ThirdPartyLibs/ArDroneSDK3/lib -o "BebopRebopAPI" ./Source/CBebopInterface.o ./Source/CCommandPacket.o ./Source/CNetworkInterface.o ./Source/CNetworkSettings.o ./Source/CVehicleInterface.o ./Source/main.o -larsdk3 -lpthread
./Source/CNetworkInterface.o: In function rebop::CNetworkInterface::ReceiveJsonCallback(unsigned char*, unsigned int, char*, void*)': /home/ubuntu/BebopRebopAPI/Build/../Source/CNetworkInterface.cpp:346: undefined reference toutil::ParseIntFromJsonString(std::string const&, std::string const&, int&)'
collect2: error: ld returned 1 exit status
make: *** [BebopRebopAPI] Error 1

Ideas?

**Comment by vladutalexandru** [comment] 2015-03-10 10:21
With what codes are you managing to pilot the drone ? In the samples you only have the part with receiving video stream, but not to pilot it...

**Comment by vignesh02** [comment] 2015-03-10 13:52
Hi djavan-bertrand,

Yes, tested when Bebop drone was flying. setAltitudeListener method was called but not the callback method. please let me know where I am going wrong in the callback method.

**Comment by vignesh02** [comment] 2015-03-10 13:53
Hi vladutalexandru,

I have taken the piloting sample code from charles github which was written C++ code.
https://github.com/spiderkeys/BebopRebopAPI

**Comment by CesarRN** [comment] 2015-03-10 13:57
Hello vignesh02, I can´t run the "BebopRebopAPI" example

https://github.com/spiderkeys/BebopRebopAPI/issues/2

Do you fix the proyect?

Thanks

**Comment by vignesh02** [comment] 2015-03-10 15:01
Hi CesaRN,

Can you please share the your email address to send you the code

**Comment by CesarRN** [comment] 2015-03-10 15:03
Hi vignesh02, of course:

ckaisser74@hotmail.com

Thanks!

**Comment by vignesh02** [comment] 2015-03-10 15:16
CesaRN,

Sent you mail. Please let me know if you have received it

**Comment by CesarRN** [comment] 2015-03-10 15:22
I had the mail.
I download the project and test it.

I send you an email with my errors.

Thanks!

**Comment by CesarRN** [comment] 2015-03-10 15:59
I think the problem is here:
ld: warning: ignoring file ../ThirdPartyLibs/ArDroneSDK3/lib/libarsdk3.a, file was built for archive which is not the architecture being linked (x86_64): ../ThirdPartyLibs/ArDroneSDK3/lib/libarsdk3.a

**Comment by vladutalexandru** [comment] 2015-03-10 17:21
Can you give us an example of a piloting command. I have the drone taking off and landing, but when i want to call the function SendPilotCommand, i must generate something more complex, with many parameters and i do not know exactly how to interpret and put values for different moves (left,right, forward, backward). You can give me an email also with the codes > vav_mad2004@yahoo.com

Thaanks Vignesh!

**Comment by vignesh02** [comment] 2015-03-11 05:13
Hi vladutalexandru,
I have mailed you the left and right PCMD command.

**Comment by vignesh02** [comment] 2015-03-11 05:14
djavan-bertrand,
Can you please help me to get altitude from drone while flying.
I have tried alot but no luck

**Comment by djavan-bertrand** [comment] 2015-03-13 16:44
Hi, 
You need to set a callback for the altitude by calling 
```c
ARCOMMANDS_Decoder_SetARDrone3PilotingStateAltitudeChangedCallback(altitudeChangedCallback, NULL);
```
Then in your callback : 
```c
void altitudeChangedCallback (double altitude, void *custom)
{
    ARSAL_PRINT(ARSAL_PRINT_ERROR, TAG, "altitude = %f", altitude);
}
```
You should see that when landed, altitude is 0 and when it flies the altitude is not 0.

Best regards, 
Djavan

**Comment by vignesh02** [comment] 2015-03-13 18:33
Hi djavan-bertrand,

The code snippet of yours and mine are same. Can you please confirm whether I have the read data from D2C port in order to get the call back values

**Comment by djavan-bertrand** [comment] 2015-03-14 13:33
Hi, 
What is your drone's firmware version ? 
Yes you have to read it from this port.

**Comment by vladutalexandru** [comment] 2015-03-18 15:11
We have the very same problem with our callback. That function is not entered and nothing is done. We have the last firmware, and we tested it while flying or while standing. No output is given from that callback...

@vignesh02 do you still have that problem or you solved it?

Does it work for somebody?

**Comment by sycbloke76** [comment] 2015-06-23 11:11
Hi Vignesh02, I was wondering if you could email me the left and right PCMD commands for the BebopRebopAPI, as you did for vladutalexandru. My email ian.sycamore@gmail.com

**Comment by sycbloke76** [comment] 2015-06-23 11:13
@vignesh02 Hi there, I was wondering if you'd be willing to send me the left and right PCMD commands for the BebopRebopAPI please... My email: ian.sycamore76@gmail.com

**Closed** 2015-06-23 13:50 UTC

**Comment by dragoon10** [comment] 2015-11-19 14:52
Hello djavan-bertrand. Can you also provide me the code for the different moves (left,right, forward, backward)

Best Regards

sjorgebruno@hotmail.com

**Comment by djavan-bertrand** [comment] 2015-11-19 16:15
Hi, 
I invite you to ask the question on the developer forum : http://forum.developer.parrot.com/.
And if you haven't already, feel free to read the documentation here: http://developer.parrot.com/docs/bebop/

Best regards, 
Djavan
